"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The real key comes from .env (gitignored). The fallback below is an obvious
# placeholder so a missing .env is caught in review rather than silently
# running with a key that is published in this repository.
SECRET_KEY = config('SECRET_KEY', default='django-insecure-PLACEHOLDER-set-SECRET_KEY-in-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    # Project apps
    'rates',
    'content',
    'team_alerts',

    # Third party
    'rest_framework',
    'corsheaders',

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=Csv(),
)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='foxexchange'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The business operates from Chennai. Timestamps are stored in UTC (USE_TZ) but
# rendered in IST everywhere — the admin list and enquiry alert emails — so the
# team reads the actual local time a lead came in.
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Shared by all three website forms (enquiry, quote, rate lock) so a
        # bot cannot triple its allowance by rotating between them. Set high
        # enough that a genuine customer who asks for a quote, locks a rate and
        # then sends an enquiry is never blocked.
        'enquiry': config('ENQUIRY_THROTTLE_RATE', default='10/hour'),
    },
}

# Branding for the Django admin, which is the single place staff edit content.
ADMIN_SITE_HEADER = 'Reddy Forex Private Limited'

# Absolute base URL used to build "open in admin" links inside alert emails.
ADMIN_BASE_URL = config('ADMIN_BASE_URL', default='http://localhost:8000')


# Email — team alerts for new website enquiries
# https://docs.djangoproject.com/en/6.0/topics/email/
#
# Leave EMAIL_HOST_USER blank in development: Django then prints emails to the
# console instead of sending them, so you can test the whole flow with no
# credentials. Set the Gmail values in .env to send for real.
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
# Gmail requires an App Password (16 chars), not your normal account password.
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default=(
        'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST_USER
        else 'django.core.mail.backends.console.EmailBackend'
    ),
)

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'no-reply@reddyforex.com')

# Who gets alerted when a website enquiry arrives. Comma-separated.
ENQUIRY_NOTIFY_EMAILS = config('ENQUIRY_NOTIFY_EMAILS', default='', cast=Csv())


# Team push notifications — internal staff only, via Chrome + Firebase Cloud
# Messaging (FCM). A staff member turns this on for their own browser from
# the "Enable push alerts" link added to the admin header (see
# team_alerts/views.EnableAlertsPageView). New enquiries then push an Urgent
# alert to every subscribed staff browser instantly, bypassing the rate limit
# below — a fresh lead should never be missed. This is in addition to, not a
# replacement for, the existing email alert in content/notifications.py.
#
# Leave FIREBASE_CREDENTIALS_JSON blank in development: subscribers still
# register and every send is still recorded (as FAILED, "FCM is not
# configured"), so the whole flow — admin tracking included — is testable
# with no credentials. Set it to the absolute path of a Firebase service
# account key file to send real pushes.
FIREBASE_CREDENTIALS_JSON = config('FIREBASE_CREDENTIALS_JSON', default='')

# A staff subscriber notified within this many minutes is skipped on the next
# Normal-priority alert. Urgent alerts (every new-enquiry alert) always
# ignore this ("urgent is free").
TEAM_ALERT_RATE_LIMIT_MINUTES = config('TEAM_ALERT_RATE_LIMIT_MINUTES', default=30, cast=int)

# Public Firebase web config — used to render the admin's "Enable push
# alerts" page and the /firebase-messaging-sw.js service worker. These are
# public client identifiers, not secrets, but still kept in .env alongside
# everything else that's environment-specific (dev vs. production Firebase
# project).
FIREBASE_WEB_API_KEY = config('FIREBASE_WEB_API_KEY', default='')
FIREBASE_WEB_AUTH_DOMAIN = config('FIREBASE_WEB_AUTH_DOMAIN', default='')
FIREBASE_WEB_PROJECT_ID = config('FIREBASE_WEB_PROJECT_ID', default='')
FIREBASE_WEB_STORAGE_BUCKET = config('FIREBASE_WEB_STORAGE_BUCKET', default='')
FIREBASE_WEB_MESSAGING_SENDER_ID = config('FIREBASE_WEB_MESSAGING_SENDER_ID', default='')
FIREBASE_WEB_APP_ID = config('FIREBASE_WEB_APP_ID', default='')
FIREBASE_WEB_VAPID_KEY = config('FIREBASE_WEB_VAPID_KEY', default='')
