"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import dj_database_url
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The real key comes from .env (gitignored). The fallback below is an obvious
# placeholder so a missing .env is caught in review rather than silently
# running with a key that is published in this repository.
SECRET_KEY = config('SECRET_KEY', default='django-insecure-PLACEHOLDER-set-SECRET_KEY-in-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Render injects the service's own hostname. Adding it automatically means a
# rename or a new instance never locks us out with a DisallowedHost error.
RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default='')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    # Project apps
    'rates',
    'content',
    'notifications',

    # Third party
    'rest_framework',
    'corsheaders',

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the admin's CSS/JS in production — Render has no separate web
    # server in front of gunicorn to do it for us.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=Csv(),
)

# The admin is a cross-origin POST target once the site is on HTTPS, so Django
# needs the scheme-qualified origins it should trust. Every HTTPS origin we
# already allow for CORS qualifies, plus this service's own URL.
CSRF_TRUSTED_ORIGINS = [o for o in CORS_ALLOWED_ORIGINS if o.startswith('https://')]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Managed hosts (Render) hand us a single DATABASE_URL; local development
# still uses the individual DB_* values from .env.
DATABASE_URL = config('DATABASE_URL', default='')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            # Reuse connections between requests instead of opening a new one
            # each time — the free database allows only a small pool.
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='foxexchange'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default='postgres'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The business operates from Chennai. Timestamps are stored in UTC (USE_TZ) but
# rendered in IST everywhere — the admin list and enquiry alert emails — so the
# team reads the actual local time a lead came in.
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compresses and fingerprints the collected files so whitenoise can
        # serve them with far-future cache headers.
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Behind Render's proxy Django only sees plain HTTP, so it has to be told the
# original request was HTTPS before it will mark cookies secure or redirect.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Shared by all three website forms (enquiry, quote, rate lock) so a
        # bot cannot triple its allowance by rotating between them. Set high
        # enough that a genuine customer who asks for a quote, locks a rate and
        # then sends an enquiry is never blocked.
        'enquiry': config('ENQUIRY_THROTTLE_RATE', default='10/hour'),
        # Push notification opt-in/opt-out: a browser only ever (re)subscribes
        # a handful of times an hour, even across tab reloads.
        'notification-subscribe': config('NOTIFICATION_SUBSCRIBE_THROTTLE_RATE', default='20/hour'),
    },
}

# Branding for the Django admin, which is the single place staff edit content.
ADMIN_SITE_HEADER = 'Reddy Forex Private Limited'

# Absolute base URL used to build "open in admin" links inside alert emails.
ADMIN_BASE_URL = config('ADMIN_BASE_URL', default='http://localhost:8000')


# Email — team alerts for new website enquiries
# https://docs.djangoproject.com/en/6.0/topics/email/
#
# Leave EMAIL_HOST_USER blank in development: Django then prints emails to the
# console instead of sending them, so you can test the whole flow with no
# credentials. Set the Gmail values in .env to send for real.
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
# Gmail requires an App Password (16 chars), not your normal account password.
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default=(
        'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST_USER
        else 'django.core.mail.backends.console.EmailBackend'
    ),
)

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'no-reply@reddyforex.com')

# Who gets alerted when a website enquiry arrives. Comma-separated.
ENQUIRY_NOTIFY_EMAILS = config('ENQUIRY_NOTIFY_EMAILS', default='', cast=Csv())


# Chrome browser push — rate alerts via Firebase Cloud Messaging (FCM)
# https://firebase.google.com/docs/cloud-messaging
#
# Leave FIREBASE_CREDENTIALS_JSON blank in development: subscribers and
# delivery attempts are still recorded (as FAILED, "FCM is not configured"),
# so the whole flow — admin tracking included — is testable with no
# credentials. Set it to the absolute path of a Firebase service account key
# file to send real pushes.
FIREBASE_CREDENTIALS_JSON = config('FIREBASE_CREDENTIALS_JSON', default='')

# A subscriber notified within this many minutes is skipped on the next
# Normal-priority alert, so customers aren't spammed on every minor rate
# tick. Urgent alerts always ignore this ("urgent is free").
NOTIFICATION_RATE_LIMIT_MINUTES = config('NOTIFICATION_RATE_LIMIT_MINUTES', default=60, cast=int)

# A currency's buy or sell rate moving by at least this many percent marks
# the auto-generated alert Urgent instead of Normal.
RATE_ALERT_URGENT_THRESHOLD_PCT = config('RATE_ALERT_URGENT_THRESHOLD_PCT', default=1.0, cast=float)
