# Generated by Django 6.0.7 on 2026-07-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Documents & KYC', max_length=60, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'FAQ category',
                'verbose_name_plural': 'FAQ categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Untick to hide this from the website without deleting it.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField(help_text='The customer’s words. Quote marks are added automatically by the site.')),
                ('name', models.CharField(help_text='e.g. Harini Venkatesh', max_length=80)),
                ('role', models.CharField(help_text='e.g. Frequent traveller, Chennai', max_length=120)),
                ('initials', models.CharField(blank=True, help_text='Shown in the avatar circle. Leave blank to derive from the name.', max_length=3)),
            ],
            options={
                'ordering': ['display_order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, help_text='Untick to hide this from the website without deleting it.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(help_text='Plain text. Leave a blank line between paragraphs.')),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Also show this question in the homepage "Before you walk in" accordion.')),
                ('category', models.ForeignKey(blank=True, help_text='Optional. Used to group questions on the FAQ page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='content.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'pk'],
                'abstract': False,
            },
        ),
    ]
