# Generated by Django 6.0.7 on 2026-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(help_text='e.g. Deborah Beck', max_length=80),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, help_text='Optional. e.g. "Google review" or "Frequent traveller, Chennai".', max_length=120),
        ),
    ]
