# Generated by Django 6.0.7 on 2026-07-29 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_testimonial_name_alter_testimonial_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(help_text='Normalised to 10 digits on save.', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(blank=True, help_text='Which service they selected.', max_length=120)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=12)),
                ('internal_note', models.TextField(blank=True, help_text='Staff notes. Never shown to the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, help_text='Set automatically when status leaves New.', null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='For spam triage.', null=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When the team alert was sent.', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Who is handling this enquiry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enquiry',
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='content_enq_status_a9ef2f_idx')],
            },
        ),
    ]
