# Generated by Django 6.0.7 on 2026-07-29 18:07

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=True, help_text='Untick to hide the "Chat with us on WhatsApp" option from the website.', verbose_name='Show WhatsApp option')),
                ('whatsapp_number', models.CharField(default='9941456261', help_text='Indian mobile number that receives customer chats. 10 digits; +91, spaces and dashes are fine and get stripped.', max_length=20, validators=[content.validators.validate_indian_phone])),
                ('whatsapp_label', models.CharField(default='Chat with us on WhatsApp', help_text='Button text shown to the customer.', max_length=80)),
                ('whatsapp_greeting', models.CharField(blank=True, default='Hello, I just sent an enquiry on your website.', help_text='Message pre-filled in the customer’s WhatsApp. Leave blank to open an empty chat.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site setting',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
