# Generated by Django 6.0.7 on 2026-07-30 09:23

from django.conf import settings
from django.db import migrations, models

URGENT = 1
OPEN_STATUSES = ('new', 'contacted')


def raise_open_rate_locks(apps, schema_editor):
    """Existing rate locks arrive at the new default (Normal), which would
    bury them under newer enquiries on the first page load after deploy.

    Only *open* ones are raised — re-flagging a closed or spam lead as urgent
    would be noise, not signal.
    """
    Lead = apps.get_model('content', 'Lead')
    Lead.objects.filter(kind='rate_lock', status__in=OPEN_STATUSES).update(priority=URGENT)


def reset_priority(apps, schema_editor):
    Lead = apps.get_model('content', 'Lead')
    Lead.objects.update(priority=3)


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_lead_and_proxies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={
                "ordering": ["priority", "-created_at"],
                "verbose_name": "lead",
                "verbose_name_plural": "all leads",
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Urgent"), (2, "High"), (3, "Normal"), (4, "Low")],
                db_index=True,
                default=3,
                help_text="Which end of the list this sits at. Set automatically when the lead arrives (rate locks come in Urgent because they expire); change it here any time.",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["priority", "-created_at"],
                name="content_lea_priorit_7cfd6a_idx",
            ),
        ),
        migrations.RunPython(raise_open_rate_locks, reset_priority),
    ]
