# Generated by Django 6.0.7 on 2026-07-30 04:31

import secrets

from django.db import migrations, models

REFERENCE_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'


def backfill_references(apps, schema_editor):
    """Any Lead saved before this migration has no reference yet — give
    existing rows one too, so the tracking feature works for them as well."""
    Lead = apps.get_model('content', 'Lead')
    existing = set(Lead.objects.exclude(reference=None).values_list('reference', flat=True))
    for lead in Lead.objects.filter(reference=None).iterator():
        while True:
            candidate = ''.join(secrets.choice(REFERENCE_ALPHABET) for _ in range(8))
            if candidate not in existing:
                existing.add(candidate)
                break
        lead.reference = candidate
        lead.save(update_fields=['reference'])


def noop_reverse(apps, schema_editor):
    pass  # nothing to undo — a blank reference is a valid pre-migration state


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_lead_and_proxies"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="reference",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Customer-facing tracking code. Generated automatically.",
                max_length=8,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(backfill_references, noop_reverse),
    ]
