# Generated by Django 6.0.7 on 2026-07-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_lead_options_lead_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
            ],
            options={
                'verbose_name': 'callback request',
                'verbose_name_plural': 'callback requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.lead',),
        ),
        migrations.AlterField(
            model_name='lead',
            name='kind',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('quote', 'Quote request'), ('rate_lock', 'Rate lock'), ('callback', 'Callback request')], db_index=True, default='enquiry', help_text='Which website form this came from.', max_length=12),
        ),
    ]
