# Generated by Django 6.0.7 on 2026-07-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_callbackrequest_alter_lead_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False, help_text='Untick (default) while the desk still needs to act on this. Tick once it\'s fully handled — resolved items drop out of the default admin list, same as "unresolved" being the working set. Never deletes anything.'),
        ),
    ]
