# Generated by Django 6.0.7 on 2026-08-01 07:35

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_lead_is_resolved"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("home_why_us", 'Homepage — "Why us" counter photo'),
                            ("about_counter", "About us — counter photo"),
                            ("about_team", "About us — front office team photo"),
                            ("service_exchange", "Service page — Foreign Exchange"),
                            ("service_money-transfer", "Service page — Money Transfer"),
                            ("service_remittance", "Service page — Money Remittance"),
                            ("service_forex-card", "Service page — Prepaid Forex Card"),
                            (
                                "service_wire-transfer",
                                "Service page — Drafts / TT / Swift Transfer",
                            ),
                            (
                                "service_student-services",
                                "Service page — Student Services",
                            ),
                        ],
                        help_text="Which spot on the site this photo fills. Each slot can only be used once — edit the existing row for that slot rather than adding a second one.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="JPEG, PNG or WebP, under 8 MB. Resized automatically if larger than 1600px on the longest side.",
                        upload_to="site-images/%Y/%m/",
                        validators=[content.validators.validate_image_upload],
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Describes the photo for screen readers and search engines. Leave blank and the slot's label is used instead.",
                        max_length=200,
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to fall back to the plain placeholder on the site without deleting the upload.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site image",
                "verbose_name_plural": "site images",
                "ordering": ["slot"],
            },
        ),
    ]
