# Generated by Django 6.0.7 on 2026-08-02 10:41

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_siteimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="address",
            field=models.TextField(
                default="Shop No 105, Challa Mall,\n17, Thyagaraya Road, T. Nagar,\nChennai, Tamil Nadu 600017",
                help_text="One address line per line — each becomes its own line on the site.",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_note",
            field=models.CharField(
                blank=True,
                default="(Opposite Globus)",
                help_text='Optional landmark note shown after the address, e.g. "(Opposite Globus)".',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="contact_email",
            field=models.EmailField(
                default="reddyforex@gmail.com",
                help_text='Public "contact us" email shown on the site. Different from the notify_* addresses below, which are where staff get alerted internally.',
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                default="https://www.facebook.com/Reddy-Forex-Private-Limited-100909432036543",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="landline_1",
            field=models.CharField(
                blank=True,
                default="044-24353596",
                help_text='Shown as entered, e.g. "044-24353596".',
                max_length=20,
                validators=[content.validators.validate_landline],
                verbose_name="Landline 1 (optional)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="landline_2",
            field=models.CharField(
                blank=True,
                default="044-24353604",
                max_length=20,
                validators=[content.validators.validate_landline],
                verbose_name="Landline 2 (optional)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="mobile_1",
            field=models.CharField(
                default="9941456261",
                help_text="Shown first everywhere on the site. 10 digits; +91, spaces and dashes are fine and get stripped.",
                max_length=20,
                validators=[content.validators.validate_indian_phone],
                verbose_name="Primary mobile",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="mobile_2",
            field=models.CharField(
                blank=True,
                default="9551699221",
                max_length=20,
                validators=[content.validators.validate_indian_phone],
                verbose_name="Second mobile (optional)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="mobile_3",
            field=models.CharField(
                blank=True,
                default="9551699055",
                max_length=20,
                validators=[content.validators.validate_indian_phone],
                verbose_name="Third mobile (optional)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="x_url",
            field=models.URLField(
                blank=True,
                default="https://x.com/ReddyForex",
                verbose_name="X (Twitter) URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                default="https://www.youtube.com/channel/UCrFuWjK4Yfma9A6RMbywE5g",
            ),
        ),
    ]
