# Generated by Django 6.0.7 on 2026-08-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_sitesetting_address_sitesetting_address_note_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RateLock",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="converted_amount",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="lock_expires_at",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="quoted_rate",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="notify_rate_locks",
        ),
        migrations.RemoveField(
            model_name="sitesetting",
            name="rate_lock_hours",
        ),
        migrations.AlterField(
            model_name="lead",
            name="kind",
            field=models.CharField(
                choices=[
                    ("enquiry", "Enquiry"),
                    ("quote", "Quote request"),
                    ("callback", "Callback request"),
                ],
                db_index=True,
                default="enquiry",
                help_text="Which website form this came from.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Urgent"), (2, "High"), (3, "Normal"), (4, "Low")],
                db_index=True,
                default=3,
                help_text="Which end of the list this sits at. Set automatically when the lead arrives; change it here any time.",
            ),
        ),
    ]
