# Generated by Django 6.0.7 on 2026-08-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_delete_ratelock_remove_lead_converted_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_legal_name',
            field=models.CharField(default='Reddy Forex Private Limited', help_text='Full registered company name — shown in the footer copyright line.', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_tagline',
            field=models.TextField(blank=True, default='Licensed and Regulated by Reserve Bank of India. Foreign currency exchange, money transfer and remittance services in Chennai since 2000.', help_text='Short description shown under the logo in the footer.'),
        ),
    ]
