# Generated by Django 6.0.7 on 2026-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_sitesetting_footer_legal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Who the money is for — e.g. the recipient of a money transfer or remittance. Optional.', max_length=150),
        ),
    ]
