# Generated by Django 6.0.7 on 2026-08-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_lead_recipient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='relationship',
            field=models.CharField(blank=True, help_text="Sender's relationship to the receiver. Required for Money Transfer requests.", max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Who the money is for — e.g. the recipient of a money transfer or remittance. Required for Money Transfer requests.', max_length=150),
        ),
    ]
