# Generated by Django 6.0.7 on 2026-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_lead_relationship_alter_lead_recipient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='slot',
            field=models.CharField(choices=[('site_logo', 'Site — logo (header)'), ('home_why_us', 'Homepage — "Why us" counter photo'), ('about_counter', 'About us — counter photo'), ('about_team', 'About us — front office team photo'), ('service_exchange', 'Service page — Foreign Exchange'), ('service_money-transfer', 'Service page — Money Transfer'), ('service_remittance', 'Service page — Money Remittance'), ('service_forex-card', 'Service page — Prepaid Forex Card'), ('service_wire-transfer', 'Service page — Drafts / TT / Swift Transfer'), ('service_student-services', 'Service page — Student Services')], help_text='Which spot on the site this photo fills. Each slot can only be used once — edit the existing row for that slot rather than adding a second one.', max_length=40, unique=True),
        ),
    ]
