# Generated by Django 6.0.7 on 2026-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_siteimage_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='slot',
            field=models.CharField(choices=[('site_logo', 'Site — logo (header)'), ('home_why_us', 'Homepage — "Why us" counter photo'), ('about_counter', 'About us — counter photo'), ('about_team', 'About us — front office team photo'), ('service_exchange', 'Service page — Foreign Exchange'), ('service_money-transfer', 'Service page — Money Transfer'), ('service_remittance', 'Service page — Money Remittance'), ('service_forex-card', 'Service page — Prepaid Forex Card'), ('service_wire-transfer', 'Service page — Drafts / TT / Swift Transfer'), ('service_student-services', 'Service page — Student Services'), ('money-transfer_western-union', 'Money Transfer — Western Union logo'), ('money-transfer_moneygram', 'Money Transfer — MoneyGram logo'), ('benefit_exchange-1', 'Service page — Foreign Exchange — Buy and sell'), ('benefit_exchange-2', 'Service page — Foreign Exchange — As per RBI guidelines'), ('benefit_exchange-3', 'Service page — Foreign Exchange — Competitive rates'), ('benefit_exchange-4', 'Service page — Foreign Exchange — Cash limit'), ('benefit_remittance-1', 'Service page — Money Remittance — Outward remittance'), ('benefit_remittance-2', 'Service page — Money Remittance — Bank partnerships'), ('benefit_remittance-3', 'Service page — Money Remittance — Purpose-based'), ('benefit_remittance-4', 'Service page — Money Remittance — LRS limit'), ('benefit_forex-card-1', 'Service page — Prepaid Forex Card — 15 currencies on one card'), ('benefit_forex-card-2', 'Service page — Prepaid Forex Card — Three year validity'), ('benefit_forex-card-3', 'Service page — Prepaid Forex Card — Where it works'), ('benefit_forex-card-4', 'Service page — Prepaid Forex Card — Encash the balance'), ('benefit_wire-transfer-1', 'Service page — Drafts / TT / Swift Transfer — SWIFT transfer'), ('benefit_wire-transfer-2', 'Service page — Drafts / TT / Swift Transfer — Demand drafts'), ('benefit_wire-transfer-3', 'Service page — Drafts / TT / Swift Transfer — Handled at the counter'), ('benefit_wire-transfer-4', 'Service page — Drafts / TT / Swift Transfer — Payment modes'), ('benefit_student-services-1', 'Service page — Student Services — University tuition fees'), ('benefit_student-services-2', 'Service page — Student Services — Students maintenance'), ('benefit_student-services-3', 'Service page — Student Services — Accommodation fees'), ('benefit_student-services-4', 'Service page — Student Services — Under LRS')], help_text='Which spot on the site this photo fills. Each slot can only be used once — edit the existing row for that slot rather than adding a second one.', max_length=40, unique=True),
        ),
    ]
