# Generated by Django 6.0.7 on 2026-08-05 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_siteimage_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hours_note',
            field=models.CharField(blank=True, help_text='Shown under the hours, e.g. "Closed on public holidays". Leave blank to show nothing.', max_length=120, verbose_name='Hours note (optional)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hours_sunday_close',
            field=models.TimeField(blank=True, help_text='Leave blank if the shop is closed on Sundays.', null=True, verbose_name='Sunday closes'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hours_sunday_open',
            field=models.TimeField(blank=True, help_text='Leave blank if the shop is closed on Sundays.', null=True, verbose_name='Sunday opens'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hours_weekday_close',
            field=models.TimeField(default=datetime.time(20, 0), help_text='When the counter closes Monday to Saturday.', verbose_name='Mon–Sat closes'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hours_weekday_open',
            field=models.TimeField(default=datetime.time(9, 30), help_text='When the counter opens Monday to Saturday.', verbose_name='Mon–Sat opens'),
        ),
    ]
