# Generated by Django 6.0.7 on 2026-08-05 14:33

import datetime
from django.db import migrations, models


PREVIOUS_DEFAULT = datetime.time(20, 0)
CORRECTED_DEFAULT = datetime.time(19, 0)


def correct_closing_time(apps, schema_editor):
    """Move the settings row off the old 8:00 PM closing time.

    Changing a field default only affects rows created afterwards, so the
    singleton created by the previous migration would otherwise keep publishing
    hours the shop does not keep. Only rows still holding the old default are
    touched — if staff have already set their own closing time, that is a
    deliberate value and this must not overwrite it.
    """
    SiteSetting = apps.get_model('content', 'SiteSetting')
    SiteSetting.objects.filter(hours_weekday_close=PREVIOUS_DEFAULT).update(
        hours_weekday_close=CORRECTED_DEFAULT,
    )


def restore_closing_time(apps, schema_editor):
    SiteSetting = apps.get_model('content', 'SiteSetting')
    SiteSetting.objects.filter(hours_weekday_close=CORRECTED_DEFAULT).update(
        hours_weekday_close=PREVIOUS_DEFAULT,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_sitesetting_hours_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='hours_weekday_close',
            field=models.TimeField(default=datetime.time(19, 0), help_text='When the counter closes Monday to Saturday.', verbose_name='Mon–Sat closes'),
        ),
        migrations.RunPython(correct_closing_time, restore_closing_time),
    ]
