# Generated by Django 6.0.7 on 2026-08-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_siteimage_hero_phone_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="needed_by",
        ),
    ]
