# Generated by Django 6.0.7 on 2026-08-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_siteimage_hero_phone_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
            ],
            options={
                'verbose_name': 'service request',
                'verbose_name_plural': 'service requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.lead',),
        ),
        migrations.AddField(
            model_name='lead',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='The answers specific to one service\'s form — e.g. "Which country?" for a money transfer, "University or institution" for student services. Every service asks something different, and none of it is worth its own column when only one of the six forms ever fills it in. Keys/labels come from SERVICE_FORMS in frontend/src/serviceForms.js; the pair is validated in content/validators.py.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='kind',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('quote', 'Quote request'), ('callback', 'Callback request'), ('service', 'Service request')], db_index=True, default='enquiry', help_text='Which website form this came from.', max_length=12),
        ),
    ]
