# Generated by Django 6.0.7 on 2026-07-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable identifier code checks against, e.g. 'exchange_rates_page'. Never rename once shipped.", max_length=60, unique=True)),
                ('name', models.CharField(help_text="Human label shown in admin, e.g. 'Exchange rates page'.", max_length=80)),
                ('description', models.TextField(blank=True, help_text='What this controls and where it takes effect — written for whoever toggles it next.')),
                ('is_enabled', models.BooleanField(default=True, help_text='Off hides the feature on the next page load. No deploy needed.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
