# Generated by Django 6.0.7 on 2026-07-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO currency code, matches rates.Currency.code', max_length=3, unique=True)),
                ('inr_rate', models.DecimalField(decimal_places=6, help_text='1 unit of this currency, in INR, per the source', max_digits=12)),
                ('source', models.CharField(help_text='Which provider this figure came from, e.g. fawazahmed0', max_length=40)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
