# Generated by Django 6.0.7 on 2026-07-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceRateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_update_enabled', models.BooleanField(default=False, help_text='When on, every fetch recalculates every currency\'s buy_rate/sell_rate from the fetched market rate plus the margins below. When off, a fetch only refreshes the "Market ref" guidance column — Currency rows are never touched.', verbose_name='Auto-update rates from market')),
                ('buy_margin', models.DecimalField(decimal_places=2, default=-1, help_text="Added to the fetched market rate to set every currency's buy_rate, e.g. -1.00 to buy ₹1 below market.", max_digits=8)),
                ('sell_margin', models.DecimalField(decimal_places=2, default=1, help_text="Added to the fetched market rate to set every currency's sell_rate, e.g. 1.00 to sell ₹1 above market.", max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'reference rate setting',
                'verbose_name_plural': 'reference rate settings',
            },
        ),
    ]
