# Generated by Django 6.0.7 on 2026-07-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_rates', '0002_referenceratesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceratesettings',
            name='primary_provider',
            field=models.CharField(choices=[('exchangerate-api', 'ExchangeRate-API (exchangerate-api.com)'), ('fawazahmed0', 'fawazahmed0/exchange-api'), ('frankfurter', 'Frankfurter')], default='exchangerate-api', help_text="Tried first on every fetch. The other two are tried, in their usual order, for whatever currencies the primary doesn't cover — e.g. if exchangerate-api has no key configured, or is down, fawazahmed0 (free, no key) is used automatically.", max_length=20),
        ),
    ]
