# Generated by Django 6.0.7 on 2026-07-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='Matches content.Lead.Kind — one row per lead type.', max_length=12, unique=True)),
                ('kind_label', models.CharField(help_text='Human-readable name shown in the admin, e.g. "Enquiry".', max_length=40)),
                ('telegram_enabled', models.BooleanField(default=True, help_text='Tick to alert Telegram subscribers when this kind of lead arrives. Untick to keep this kind out of Telegram entirely — the email alert and the admin inbox are unaffected either way.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'lead alert rule',
                'verbose_name_plural': 'lead alert rules (Telegram checklist)',
                'ordering': ['kind_label'],
            },
        ),
    ]
