# Generated by Django 6.0.7 on 2026-08-14 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="McpToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Who or what uses this token, e.g. "Claude desktop — Priya". Shown in the audit log against every call it makes.',
                        max_length=80,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "token_hint",
                    models.CharField(
                        editable=False,
                        help_text="The last few characters of the token, so you can tell two rows apart.",
                        max_length=12,
                    ),
                ),
                (
                    "can_read",
                    models.BooleanField(
                        default=True,
                        help_text="List images, testimonials and FAQs. Safe: reads published and unpublished content but changes nothing.",
                    ),
                ),
                (
                    "can_write_images",
                    models.BooleanField(
                        default=False,
                        help_text="Upload photos into site image slots and edit their alt text.",
                    ),
                ),
                (
                    "can_write_content",
                    models.BooleanField(
                        default=False,
                        help_text="Create and edit testimonials and FAQs. New items always arrive unpublished for a human to review — see docs/mcp-server.md.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to revoke immediately without deleting the audit trail.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. After this moment the token stops working. Leave blank for no expiry.",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "MCP token",
                "verbose_name_plural": "MCP tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="McpCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_name",
                    models.CharField(
                        blank=True,
                        help_text="Copied at call time so the log still names the caller after the token is deleted.",
                        max_length=80,
                    ),
                ),
                ("tool", models.CharField(max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("denied", "Denied"),
                        ],
                        max_length=8,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null once the token itself has been deleted — the log entry outlives it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="mcp_server.mcptoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP call log",
                "verbose_name_plural": "MCP call log",
                "ordering": ["-created_at"],
            },
        ),
    ]
