# Generated by Django 6.0.7 on 2026-07-29 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0005_lead_and_proxies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.CharField(max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("urgent", "Urgent")],
                        db_index=True,
                        default="normal",
                        help_text="Urgent alerts bypass the per-staff-member rate limit and are sent at high FCM/webpush priority.",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Subscribers this alert was attempted against.",
                    ),
                ),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("fail_count", models.PositiveIntegerField(default=0)),
                (
                    "skipped_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Subscribers skipped by the per-staff-member rate limit (Normal priority only).",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank for alerts generated automatically from a new enquiry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set automatically for enquiry alerts. Optional otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_alerts",
                        to="content.lead",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.Case(
                        models.When(priority="urgent", then=models.Value(0)),
                        default=models.Value(1),
                        output_field=models.IntegerField(),
                    ),
                    "-created_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamPushSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fcm_token",
                    models.TextField(
                        help_text="FCM registration token issued to this browser.",
                        unique=True,
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Turned off automatically once FCM reports this token as no longer registered.",
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Consecutive failed sends. Reset on the next success.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Updated every time the browser re-registers this token.",
                    ),
                ),
                (
                    "last_notified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Used for the per-staff-member rate limit on Normal priority alerts. Urgent alerts ignore it.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The staff member this browser belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamAlertDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (rate limit)"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("fcm_message_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="team_alerts.teamalert",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="team_alerts.teampushsubscriber",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "team alert deliveries",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-attempted_at"],
                        name="team_alerts_status_57018a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("alert", "subscriber"),
                        name="unique_team_delivery_per_subscriber",
                    )
                ],
            },
        ),
    ]
