# Generated by Django 6.0.7 on 2026-07-31 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0007_callbackrequest_alter_lead_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Staff member's name, for your own reference.", max_length=100)),
                ('chat_id', models.CharField(help_text="Telegram chat ID. Have the staff member message the bot once, then find their chat_id via the bot's recent updates — see docs/telegram-bot.md for the exact steps.", max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to stop sending this person alerts, without deleting their record.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=10)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_deliveries', to='content.lead')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='telegram_alerts.telegramsubscriber')),
            ],
            options={
                'verbose_name_plural': 'telegram deliveries',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['status', '-attempted_at'], name='telegram_al_status_1d159e_idx')],
                'constraints': [models.UniqueConstraint(fields=('lead', 'subscriber'), name='unique_telegram_delivery_per_subscriber')],
            },
        ),
    ]
