# Generated by Django 6.0.7 on 2026-07-31 07:55

import django.db.models.deletion
import telegram_alerts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=telegram_alerts.models._generate_token, editable=False, max_length=64, unique=True)),
                ('label', models.CharField(help_text='Who this invite is for, e.g. "Ravi — counter". Becomes the subscriber\'s name once claimed.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending — not yet scanned'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(default=telegram_alerts.models._default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_invite', to='telegram_alerts.telegramsubscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
