# Generated by Django 6.0.7 on 2026-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO currency code, e.g. USD', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Full name, e.g. US Dollar', max_length=60)),
                ('country_code', models.CharField(help_text='ISO country code for the badge, e.g. US', max_length=2)),
                ('region', models.CharField(choices=[('Europe', 'Europe'), ('Asia-Pacific', 'Asia-Pacific'), ('Middle East', 'Middle East'), ('Americas', 'Americas')], default='Asia-Pacific', max_length=20)),
                ('buy_rate', models.DecimalField(decimal_places=4, help_text='We buy at this rate (INR)', max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=4, help_text='We sell at this rate (INR)', max_digits=10)),
                ('change_pct', models.DecimalField(decimal_places=2, default=0, help_text='24h change, percent', max_digits=6)),
                ('is_popular', models.BooleanField(default=False, help_text='Show on the homepage board and ticker')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['display_order', 'code'],
            },
        ),
    ]
