# Generated by Django 6.0.7 on 2026-07-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConverterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee_percent', models.DecimalField(decimal_places=2, default=0.4, help_text='Fee charged on top of the exchange rate, as a percent (e.g. 0.4 = 0.4%)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'converter setting',
                'verbose_name_plural': 'converter settings',
            },
        ),
    ]
