# Generated by Django 6.0.7 on 2026-07-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_convertersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show this currency anywhere in the UI (rate table, converter, homepage board). Untick to hide it without deleting it.'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the rate table'),
        ),
    ]
