# Generated by Django 6.0.7 on 2026-07-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_currency_is_visible_alter_currency_display_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConverterSetting',
        ),
    ]
