# Generated by Django 6.0.7 on 2026-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_delete_convertersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='rate_type',
            field=models.CharField(choices=[('cash', 'Cash (currency notes)'), ('forex_card', 'Forex card')], default='cash', help_text='Which counter product this row prices — cash or forex card. Each currency can have one row per type.', max_length=20),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='ISO currency code, e.g. USD', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('code', 'rate_type')},
        ),
    ]
