# Generated by Django 6.0.7 on 2026-07-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_currency_rate_type_alter_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='auto_update_from_reference',
            field=models.BooleanField(default=False, help_text='When on, buy_rate/sell_rate are recalculated automatically from the fetched market rate plus the margins below, on every scheduled or manual reference-rate fetch.'),
        ),
        migrations.AddField(
            model_name='currency',
            name='buy_margin',
            field=models.DecimalField(decimal_places=4, default=-1, help_text='Added to the fetched market rate to set buy_rate automatically, e.g. -1.00 to buy ₹1 below market. Only used when auto-update is on.', max_digits=8),
        ),
        migrations.AddField(
            model_name='currency',
            name='sell_margin',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Added to the fetched market rate to set sell_rate automatically, e.g. 1.00 to sell ₹1 above market. Only used when auto-update is on.', max_digits=8),
        ),
    ]
