# Generated by Django 6.0.7 on 2026-07-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_currency_auto_update_from_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='buy_margin',
            field=models.DecimalField(decimal_places=2, default=-1, help_text='Added to the fetched market rate to set buy_rate automatically, e.g. -1.00 to buy ₹1 below market. Only used when auto-update is on.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='currency',
            name='buy_rate',
            field=models.DecimalField(decimal_places=2, help_text='We buy at this rate (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sell_margin',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Added to the fetched market rate to set sell_rate automatically, e.g. 1.00 to sell ₹1 above market. Only used when auto-update is on.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sell_rate',
            field=models.DecimalField(decimal_places=2, help_text='We sell at this rate (INR)', max_digits=10),
        ),
    ]
