# Generated by Django 6.0.7 on 2026-07-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_alter_currency_buy_margin_alter_currency_buy_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='auto_update_from_reference',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='buy_margin',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='sell_margin',
        ),
    ]
