# Generated by Django 6.0.7 on 2026-08-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0010_normalize_currency_code_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='change_pct',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='is_popular',
        ),
    ]
