# Generated by Django 6.0.7 on 2026-08-04 14:09

from decimal import Decimal

from django.db import migrations, models


def backfill_change_pct(apps, schema_editor):
    """The AddField above lands every row at the model default (0) — recompute the real
    buy/sell spread immediately rather than leaving the column wrong until the next fetch."""
    Currency = apps.get_model('rates', 'Currency')
    for currency in Currency.objects.all():
        if not currency.buy_rate:
            continue
        spread = ((currency.sell_rate - currency.buy_rate) / currency.buy_rate * 100).quantize(Decimal('0.01'))
        Currency.objects.filter(pk=currency.pk).update(change_pct=spread)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0011_remove_currency_change_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='change_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Buy/sell spread, percent. Recalculated automatically whenever a reference-rate fetch applies a new buy/sell rate — edit by hand here to override that value.', max_digits=6),
        ),
        migrations.RunPython(backfill_change_pct, noop_reverse),
    ]
