# Generated by Django 6.0.7 on 2026-08-04 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='#E2571F', help_text='Primary accent: buttons, links, eyebrow labels, active underlines.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('brand_dark', models.CharField(default='#C4460F', help_text='Hover/pressed state for anything using the brand colour. Should be a shade darker than it.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('accent', models.CharField(default='#F0A07A', help_text='Lighter brand tone, used for eyebrow text on dark navy panels where the brand colour is too dim.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('ink', models.CharField(default='#0B1B33', help_text='Headings, and the background of the dark page-hero sections.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('ink_deep', models.CharField(default='#08152A', help_text='The footer background — a touch darker than the heading colour.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('surface', models.CharField(default='#FFFFFF', help_text='Page background and card background.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('surface_alt', models.CharField(default='#F8F7F5', help_text='The warm off-white used for alternating page sections and form fields.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('line', models.CharField(default='#E7E4DF', help_text='Default border/divider colour on light backgrounds.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('body_text', models.CharField(default='#435066', help_text='Paragraph text.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('muted_text', models.CharField(default='#6B7688', help_text='Secondary text: captions, help text, card descriptions.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('success', models.CharField(default='#2FA36B', help_text='Rate moved up, form submitted, WhatsApp panel.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('danger', models.CharField(default='#C0492C', help_text='Rate moved down, validation errors.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')])),
                ('font_sans', models.CharField(default="'Instrument Sans', system-ui, sans-serif", help_text='A CSS font-family stack, most-preferred first, e.g. "\'Instrument Sans\', system-ui, sans-serif". Quote any family whose name has a space. If you name a Google font here, add it to the fonts URL below or the browser cannot load it.', max_length=200, verbose_name='Body font stack')),
                ('font_serif', models.CharField(default="'Instrument Serif', serif", help_text='A CSS font-family stack, most-preferred first, e.g. "\'Instrument Sans\', system-ui, sans-serif". Quote any family whose name has a space. If you name a Google font here, add it to the fonts URL below or the browser cannot load it.', max_length=200, verbose_name='Heading font stack')),
                ('font_mono', models.CharField(default="'IBM Plex Mono', monospace", help_text='A CSS font-family stack, most-preferred first, e.g. "\'Instrument Sans\', system-ui, sans-serif". Quote any family whose name has a space. If you name a Google font here, add it to the fonts URL below or the browser cannot load it.', max_length=200, verbose_name='Mono font stack')),
                ('fonts_url', models.URLField(blank=True, default='https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600;700&family=Instrument+Serif:ital@0;1&family=IBM+Plex+Mono:wght@400;500&display=swap', help_text='Loaded before the page renders. Pick fonts at fonts.google.com, copy the URL out of its "@import"/"link" snippet, and make sure every family named above appears in it. Leave blank to use only fonts already installed on the visitor\'s device.', max_length=500, verbose_name='Webfont stylesheet URL')),
                ('base_font_size', models.DecimalField(decimal_places=1, default=14.5, help_text='Pixel size of standard UI text, and the anchor for every other size on the site — raising it scales all text up proportionally. Between 10 and 24.', max_digits=4, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(24)])),
                ('heading_scale', models.DecimalField(decimal_places=2, default=1.0, help_text='Extra multiplier applied to large headings only, on top of the base size. 1.0 keeps them in their current proportion to body text; above 1.0 gives bigger, more magazine-like headings without touching paragraphs or UI text; below 1.0 tones them down.', max_digits=4, validators=[django.core.validators.MinValueValidator(0.6), django.core.validators.MaxValueValidator(2.0)])),
                ('radius', models.PositiveSmallIntegerField(default=14, help_text='Corner rounding on cards and panels, in pixels. 0 for square corners.', validators=[django.core.validators.MaxValueValidator(40)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'theme',
            },
        ),
    ]
