# Generated by Django 6.0.7 on 2026-08-04 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='accent',
            field=models.CharField(default='#DCB35F', help_text='Lighter brand tone, used for eyebrow text on dark navy panels where the brand colour is too dim.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='body_text',
            field=models.CharField(default='#3D4A4B', help_text='Paragraph text.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='brand',
            field=models.CharField(default='#A87B2C', help_text='Primary accent: buttons, links, eyebrow labels, active underlines.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='brand_dark',
            field=models.CharField(default='#8C6624', help_text='Hover/pressed state for anything using the brand colour. Should be a shade darker than it.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='danger',
            field=models.CharField(default='#B5482E', help_text='Rate moved down, validation errors.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='ink',
            field=models.CharField(default='#0E3B3E', help_text='Headings, and the background of the dark page-hero sections.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='ink_deep',
            field=models.CharField(default='#072A2C', help_text='The footer background — a touch darker than the heading colour.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='line',
            field=models.CharField(default='#DDD2B4', help_text='Default border/divider colour on light backgrounds.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='muted_text',
            field=models.CharField(default='#6B7877', help_text='Secondary text: captions, help text, card descriptions.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='success',
            field=models.CharField(default='#2E8B62', help_text='Rate moved up, form submitted, WhatsApp panel.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='surface',
            field=models.CharField(default='#F7F2E7', help_text='Page background and card background.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='surface_alt',
            field=models.CharField(default='#EDE3CC', help_text='The warm off-white used for alternating page sections and form fields.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
    ]
