# Generated by Django 6.0.7 on 2026-08-05 14:49

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


# The palette and base size this migration replaces. Only a row still holding all
# of these is updated: that means nobody has touched the theme in the admin, so it
# is the shipped default rather than somebody's deliberate choice.
SUPERSEDED = {
    'brand': '#A87B2C',
    'brand_dark': '#8C6624',
    'surface': '#F7F2E7',
    'surface_alt': '#EDE3CC',
    'line': '#DDD2B4',
    'body_text': '#3D4A4B',
    'muted_text': '#6B7877',
}
REPLACEMENT = {
    'brand': '#8C6420',
    'brand_dark': '#74521A',
    'surface': '#FFFFFF',
    'surface_alt': '#F1F4F3',
    'line': '#DCE3E2',
    'body_text': '#2F3B3B',
    'muted_text': '#5A6767',
}


def adopt_new_palette(apps, schema_editor):
    """Move an untouched theme row onto the new palette and reading size.

    Changing a field default only affects rows created afterwards, so the
    singleton would otherwise keep serving the old parchment palette from
    /api/theme/ — and those inline custom properties outrank the stylesheet,
    so the site would render in the old colours no matter what theme.css says.

    Deliberately all-or-nothing: if any of the seven colours differs, someone
    has been in the admin picking colours and none of them are overwritten.
    """
    ThemeSetting = apps.get_model('theming', 'ThemeSetting')
    rows = ThemeSetting.objects.filter(**SUPERSEDED)
    # base_font_size moves with the palette, but also on its own if the colours
    # were customised — 14.5 was never a deliberate choice, it was the old default.
    rows.update(**REPLACEMENT)
    ThemeSetting.objects.filter(base_font_size=Decimal('14.5')).update(base_font_size=Decimal('16'))


def restore_old_palette(apps, schema_editor):
    ThemeSetting = apps.get_model('theming', 'ThemeSetting')
    ThemeSetting.objects.filter(**REPLACEMENT).update(**SUPERSEDED)
    ThemeSetting.objects.filter(base_font_size=Decimal('16')).update(base_font_size=Decimal('14.5'))


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0002_alter_themesetting_accent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='base_font_size',
            field=models.DecimalField(decimal_places=1, default=16, help_text='Pixel size of standard UI text, and the anchor for every other size on the site — raising it scales all text up proportionally. Between 10 and 24; 16 is the default and anything below about 14 gets hard to read on a phone.', max_digits=4, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='body_text',
            field=models.CharField(default='#2F3B3B', help_text='Paragraph text. Needs at least 4.5:1 against the surface colour.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='brand',
            field=models.CharField(default='#8C6420', help_text='Primary accent: buttons, links, eyebrow labels, active underlines. Keep it dark enough that white button text stays readable on it (at least 4.5:1).', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='brand_dark',
            field=models.CharField(default='#74521A', help_text='Hover/pressed state for anything using the brand colour. Should be a shade darker than it.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='line',
            field=models.CharField(default='#DCE3E2', help_text='Default border/divider colour on light backgrounds.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='muted_text',
            field=models.CharField(default='#5A6767', help_text='Secondary text: captions, help text, card descriptions. Every fainter shade on the site is mixed from this, so lightening it lightens all of them — keep it at 4.5:1 or better against the surface.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='surface',
            field=models.CharField(default='#FFFFFF', help_text='Page background and card background.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='surface_alt',
            field=models.CharField(default='#F1F4F3', help_text='The off-white used for alternating page sections and form fields. Keep it close to the surface colour — it is meant to separate sections, not to be noticed.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.RunPython(adopt_new_palette, restore_old_palette),
    ]
