# Generated by Django 6.0.7 on 2026-08-05 15:06

import django.core.validators
from django.db import migrations, models


# The teal + bronze palette this replaces, and the black/white/gold one that does.
# Same all-or-nothing rule as migration 0003: a row is only moved if every one of
# these still matches, which means nobody has picked colours in the admin.
SUPERSEDED = {
    'brand': '#8C6420',
    'brand_dark': '#74521A',
    'accent': '#DCB35F',
    'ink': '#0E3B3E',
    'ink_deep': '#072A2C',
    'surface_alt': '#F1F4F3',
    'line': '#DCE3E2',
    'body_text': '#2F3B3B',
    'muted_text': '#5A6767',
    'success': '#2E8B62',
    'danger': '#B5482E',
}
REPLACEMENT = {
    'brand': '#8A6A22',
    'brand_dark': '#6E5219',
    'accent': '#D4AF37',
    'ink': '#111111',
    'ink_deep': '#000000',
    'surface_alt': '#F7F7F5',
    'line': '#E5E5E1',
    'body_text': '#1C1C1C',
    'muted_text': '#6B6B67',
    'success': '#1F7A4C',
    'danger': '#A8342A',
}


def adopt_three_colour_palette(apps, schema_editor):
    """Move an untouched theme row onto black, white and gold.

    /api/theme/ writes these onto :root as inline custom properties, which
    outrank the stylesheet — so without this the site would keep rendering in
    teal no matter what theme.css says.
    """
    ThemeSetting = apps.get_model('theming', 'ThemeSetting')
    ThemeSetting.objects.filter(**SUPERSEDED).update(**REPLACEMENT)


def restore_teal_palette(apps, schema_editor):
    ThemeSetting = apps.get_model('theming', 'ThemeSetting')
    ThemeSetting.objects.filter(**REPLACEMENT).update(**SUPERSEDED)


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0003_alter_themesetting_base_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='accent',
            field=models.CharField(default='#D4AF37', help_text='The bright gold. Used on the black panels, on hairlines, and as a fill behind BLACK text — it is too light to set small text on white, which is what brand is for.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='body_text',
            field=models.CharField(default='#1C1C1C', help_text='Paragraph text. Needs at least 4.5:1 against the surface colour.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='brand',
            field=models.CharField(default='#8A6A22', help_text='The accent colour where it has to work as small text on white: eyebrow labels, links, step numbers. Must clear 4.5:1 against the surface, which is why it is a deeper gold than the accent below rather than the same value.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='brand_dark',
            field=models.CharField(default='#6E5219', help_text='Hover/pressed state for anything using the brand colour. Should be a shade darker than it.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='danger',
            field=models.CharField(default='#A8342A', help_text='Rate moved down, and validation errors. A signal, not a brand colour.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='ink',
            field=models.CharField(default='#111111', help_text='Headings, buttons, and the background of the dark page sections.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='ink_deep',
            field=models.CharField(default='#000000', help_text='The footer background — a touch darker than the heading colour.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='line',
            field=models.CharField(default='#E5E5E1', help_text='Default border/divider colour on light backgrounds.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='muted_text',
            field=models.CharField(default='#6B6B67', help_text='Secondary text: captions, help text, card descriptions. Every fainter shade on the site is mixed from this, so lightening it lightens all of them — keep it at 4.5:1 or better against the surface.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='success',
            field=models.CharField(default='#1F7A4C', help_text='Rate moved up. A signal, not a brand colour — nothing decorative should use it.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='surface_alt',
            field=models.CharField(default='#F7F7F5', help_text='The off-white used for alternating page sections and form fields. Keep it close to the surface colour — it is meant to separate sections, not to be noticed.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.RunPython(adopt_three_colour_palette, restore_teal_palette),
    ]
