# Generated by Django 6.0.7 on 2026-08-05 15:59

import django.core.validators
from django.db import migrations, models

# The black/white/gold palette this replaces, and the indigo/cream/ink one that does.
# Same all-or-nothing rule as migrations 0003 and 0004: a row only moves if every one
# of these still matches, meaning nobody has picked colours in the admin.
SUPERSEDED = {
    'brand': '#8A6A22', 'brand_dark': '#6E5219', 'accent': '#D4AF37',
    'ink': '#111111', 'ink_deep': '#000000',
    'surface_alt': '#F7F7F5', 'line': '#E5E5E1',
    'body_text': '#1C1C1C', 'muted_text': '#6B6B67',
}
REPLACEMENT = {
    'brand': '#26307A', 'brand_dark': '#1C2560', 'accent': '#9AA2E0',
    'ink': '#14161A', 'ink_deep': '#0D0F12',
    'surface_alt': '#F6F3EC', 'line': '#E4DFD4',
    'body_text': '#3A3D45', 'muted_text': '#5F636D',
}


def adopt_indigo_palette(apps, schema_editor):
    """Move an untouched theme row onto indigo, cream and ink.

    /api/theme/ writes these onto :root as inline custom properties, which outrank
    the stylesheet — so without this the site keeps rendering in the old palette
    no matter what theme.css says.
    """
    ThemeSetting = apps.get_model('theming', 'ThemeSetting')
    ThemeSetting.objects.filter(**SUPERSEDED).update(**REPLACEMENT)


def restore_gold_palette(apps, schema_editor):
    ThemeSetting = apps.get_model('theming', 'ThemeSetting')
    ThemeSetting.objects.filter(**REPLACEMENT).update(**SUPERSEDED)


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0004_alter_themesetting_accent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='accent',
            field=models.CharField(default='#9AA2E0', help_text='A light tint of the brand, used only for eyebrow text and hairlines on the dark brand panel, where the brand colour itself would be invisible.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='body_text',
            field=models.CharField(default='#3A3D45', help_text='Paragraph text. Needs at least 4.5:1 against the page ground.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='brand',
            field=models.CharField(default='#26307A', help_text='Every action: buttons, links, active nav, and the one dark panel per page. Needs to work both as a fill under white text and as small text on the page ground, so keep it dark enough for 4.5:1 in both directions.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='brand_dark',
            field=models.CharField(default='#1C2560', help_text='Hover/pressed state for anything using the brand colour. Should be a shade darker than it.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='ink',
            field=models.CharField(default='#14161A', help_text='Headings, the footer, and dark surfaces that are NOT actions — a table header, an address card. Buttons use the brand colour, not this.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='ink_deep',
            field=models.CharField(default='#0D0F12', help_text='The footer background — a touch darker than the heading colour.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='line',
            field=models.CharField(default='#E4DFD4', help_text='Default border/divider colour on light backgrounds.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='muted_text',
            field=models.CharField(default='#5F636D', help_text='Secondary text: captions, help text, card descriptions. Every fainter shade on the site is mixed from this, so lightening it lightens all of them — keep it at 4.5:1 or better against the page ground.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='surface',
            field=models.CharField(default='#FFFFFF', help_text='CARD background. Deliberately lighter than the page ground below, which is what makes every card read as raised — do not set this to the same value as the page ground.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='surface_alt',
            field=models.CharField(default='#F6F3EC', help_text='The page ground, and the fill inside form fields. This is the colour most of the site is; cards sit on top of it in the lighter surface colour above.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.RunPython(adopt_indigo_palette, restore_gold_palette),
    ]
