# Generated by Django 6.0.7 on 2026-08-06 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0005_indigo_cream_ink_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='accent',
            field=models.CharField(default='#B08B3E', help_text='A gold accent used for eyebrow text, stamps and small dividers — on both the cream ground and the dark brand panel, where the brand colour itself would be invisible.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='body_text',
            field=models.CharField(default='#33364A', help_text='Paragraph text. Needs at least 4.5:1 against the page ground.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='brand',
            field=models.CharField(default='#1E2260', help_text='Every action: buttons, links, active nav, and the one dark panel per page. Needs to work both as a fill under white text and as small text on the page ground, so keep it dark enough for 4.5:1 in both directions.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='brand_dark',
            field=models.CharField(default='#171B58', help_text='Hover/pressed state for anything using the brand colour. Should be a shade darker than it.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='font_mono',
            field=models.CharField(default="'JetBrains Mono', monospace", help_text='A CSS font-family stack, most-preferred first, e.g. "\'Instrument Sans\', system-ui, sans-serif". Quote any family whose name has a space. If you name a Google font here, add it to the fonts URL below or the browser cannot load it.', max_length=200, verbose_name='Mono font stack'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='font_sans',
            field=models.CharField(default="'Manrope', system-ui, sans-serif", help_text='A CSS font-family stack, most-preferred first, e.g. "\'Instrument Sans\', system-ui, sans-serif". Quote any family whose name has a space. If you name a Google font here, add it to the fonts URL below or the browser cannot load it.', max_length=200, verbose_name='Body font stack'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='fonts_url',
            field=models.URLField(blank=True, default='https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Manrope:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;700&display=swap', help_text='Loaded before the page renders. Pick fonts at fonts.google.com, copy the URL out of its "@import"/"link" snippet, and make sure every family named above appears in it. Leave blank to use only fonts already installed on the visitor\'s device.', max_length=500, verbose_name='Webfont stylesheet URL'),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='ink',
            field=models.CharField(default='#1B1E4B', help_text='Headings, the footer, and dark surfaces that are NOT actions — a table header, an address card. Buttons use the brand colour, not this.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='ink_deep',
            field=models.CharField(default='#161A52', help_text='The footer background — a touch darker than the heading colour.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='line',
            field=models.CharField(default='#E3E1EC', help_text='Default border/divider colour on light backgrounds.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='muted_text',
            field=models.CharField(default='#5A5D78', help_text='Secondary text: captions, help text, card descriptions. Every fainter shade on the site is mixed from this, so lightening it lightens all of them — keep it at 4.5:1 or better against the page ground.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='surface_alt',
            field=models.CharField(default='#F4F1EA', help_text='The page ground, and the fill inside form fields. This is the colour most of the site is; cards sit on top of it in the lighter surface colour above.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour like #E2571F (or the 3-digit form, #E51).')]),
        ),
    ]
